### ISSUE TITLE
[Performance Issue]Intellisence is Either Slow or Not working  in a File having Large Resource or Library import 

### ISSUE THREAD

**Issue by Deep-Adhikary** [robocorp/robotframework-lsp#84]
It is showing loading. and after 40 sec it either shows keyword list or nothing. Though it is working for file having  few number of resource and library import.
![image](https://user-images.githubusercontent.com/13049680/83733863-cb417e80-a66b-11ea-90c1-41655ba83e63.png)

**Comment by fabioz** [comment]
@Deep-Adhikary can you provide the logs when this happens?

The logs may be obtained by adding the settings below to your user settings (and restarting robotframework-lsp afterwards -- please remove any prior log if you had already enabled it, also, please just open the editor, do a completion, close the editor and then get the logs, so that it's not cluttered by other actions):

"robot.language-server.args": ["-vv", "--log-file=<path_to_directory>/robotframework_ls.log"]

Note: afterwards, you should probably remove the logging (logging makes the language server slower -- if you have it currently on, turning it off may solve your issue).

**Comment by Deep-Adhikary** [comment]
**@fabioz** I know log will be helpful.. Unfortunately the issue have been observed in **production Azure VM** where I have very limited access. Thats why I am unable to share the log.
As an alternative I will try to reproduce the issue in my local system and update you. If I get a sample robot test repository handy, that will be more helpful. Please let me know if you have any..

**Comment by fabioz** [comment]
Ok, I'll be waiting for the repro.

**Comment by fabioz** [comment]
I did find one issue where code-completion and code-analysis were competing for the same resource (this has been fixed in `0.3.0`), so, hopefully this has already improved.

**Comment by Deep-Adhikary** [comment]
Sorry for delayed response. The issue is still present. Unfortunately it is not reproducible in my local system due to enhanced system configuration or lack of real-life code base.  Though they are reproducible in my azure VDIs. Unfortunately the code base is proprietary and not open source. As your log is collecting all the keywords and list of variables in logs, This is not possible for me to share the detailed log. Moreover, the system is completely isolated from my local and github is not accessible from that system.

**Comment by Deep-Adhikary** [comment]
I am very keen to use this framework there as it is the most complete plugin is vscode for robotframework script development as of now. Unfortunately I cannot use it due to this. :(
Presently I am using 
**Robot Framework Intellisense FORK**
by @Snooz82 
I do see that he/she is also a contributor in this project. This plugin is perfectly working there. But it does not have the required support for debugging and linting.
